version: '3'
services: 
  app:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     PORT: 3000
   ports:
     - 3000:3000
   depends_on:
     - postgres
   networks:
     - api_network

  postgres:
      image: postgres:14.0-alpine
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_PORT}
        POSTGRES_SERVICE: ${DB_HOST}
      restart: always
      ports:
        - 5432:5432
      env_file:
        - .env
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      networks:
        - api_network

volumes:
  postgres_data:

networks:
  api_network:
    driver: bridge